yarnPath: .yarn/releases/yarn-4.0.2.cjs
packageExtensions:
  "drizzle-kit@*":
    dependencies:
      "drizzle-orm": "*"
  "@drizzle-team/studio@*":
    dependencies:
      "drizzle-orm": "*"
nodeLinker: node-modules