FROM node:lts-alpine

RUN apk add git bash curl
RUN bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

WORKDIR /app

COPY . .

RUN bash ./apps/api/util/setup.sh

RUN yarn
RUN yarn build:api

CMD yarn start:api