FROM node:lts-alpine

RUN apk add git bash curl
RUN bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

WORKDIR /app

COPY . .

RUN yarn
RUN yarn build:frontend

CMD yarn start:frontend