import "~/styles/globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Roboto } from "next/font/google";
import { StyledEngineProvider } from '@mui/material/styles';
import NextAuthProvider from "../components/NextAuthProvider";

const roboto = Roboto({
  weight: ['400'],
  variable: '--font-sans',
  subsets: ['latin']
});

export const metadata = {
  title: "sern Automata GUI",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${roboto.variable}`}>
        <NextAuthProvider>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <StyledEngineProvider injectFirst>
                {children}
            </StyledEngineProvider>
          </AppRouterCacheProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
