version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: automatadev
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5431:5432