name: Test
on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Hello World
        run: echo "Hello World"
      - name: cat drizzle.config.ts
        run: cat drizzle.config.ts
