name: Update website and bot's API docs

on:
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'sern-handler/website'
          token: ${{ secrets.AUTOMATA_TOKEN }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Clone handler repo & install deps
        run: |
          git clone https://github.com/sern-handler/handler.git ../sernHandlerV2
          cd ../sernHandlerV2
          yarn --inmutable
          yarn build:dev
          cd ${{ github.workspace }}
      - name: Move docusaurus config files
        run: |
          mv ./docusaurus.config.js ./original.docusaurus.config.js
          mv ./docgen.docusaurus.config.js ./docusaurus.config.js
      - name: Build website
        run: yarn build
      - name: Revert moved config files
        run: |
          mv docusaurus.config.js docgen.docusaurus.config.js
          mv original.docusaurus.config.js docusaurus.config.js
      - name: Push to repo
        run: |
          git add .
          git commit -m "docs: Update API section"
          git push
  community-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'sern-handler/sern-community'
          token: ${{ secrets.AUTOMATA_TOKEN }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install typedoc
        run: yarn global add typedoc
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Clone handler repo & install deps
        run: |
          git clone https://github.com/sern-handler/handler.git ../sernHandlerV2
          cd ../sernHandlerV2
          yarn --inmutable
          yarn build:dev
          cd ${{ github.workspace }}
      - name: Generate API docs
        run: typedoc --json ./docs.json --pretty --entryPoints ../sernHandlerV2/src/index.ts --tsconfig ../sernHandlerV2/tsconfig.json --excludeExternals
      - name: Push to repo
        run: |
          git add .
          git commit -m "docs: Update API section"
          git push